### ISSUE TITLE
Missing interpolate.py

### ISSUE THREAD

**Issue by nikhilweee** [albertaparicio/tfg-voice-conversion#5]
Hi, I'm trying to extract features from my own dataset but I find that you use `interpolate.py` during alignment, which isn't present in the repository or elsewhere. Could you please add the file and/or describe what it does?

**Comment by albertaparicio** [comment]
Dear Nikhil,

First and foremost, thank you for your interest in my project.

The interpolate.py script comes from [santi-pdp/ahoproc_tools](https://github.com/santi-pdp/ahoproc_tools/blob/master/ahoproc_tools/interpolate.py)

I have added this url to the code of my scripts so that this does not happen anymore (you are the 2nd person that asks me for that script)

I hope you find this project useful

Cheers

**Comment by nikhilweee** [comment]
Dear Albert,
Thank you very much for your help. I'm sorry I should have read the issues before opening another one. On a side note, if possible can you post some references that would help me understand this project better?

**Comment by albertaparicio** [comment]
I'll summarize this project in a few words:

This repository contains the code of my bachelor thesis project. It is a Deep Learning based Voice Conversion system.

On May 7th I'll publish the thesis, which will be linked in the main page. There you will find detailed information of all the project

Hope that helps :)

**Comment by nikhilweee** [comment]
Thank you so much! I'm looking forward to it!
